### ISSUE TITLE
Crash on 1b0m1fw.tie

### ISSUE THREAD

**Issue by keiranhalcyon31** [MikeG621/MissionVerify#2]
Platform: XWA

MissionVerify crashes on 1b0m1fw.tie, the very first mission of the game!  (All the prologue missions (battle "0"), actually.)

**Comment by MikeG621** [comment]
After I'm finished updating to my current standards, I'll see if it still
hangs up.

--
Michael Gaisser
850-396-4535

**Comment by MikeG621** [comment]
The crash is occurring because over 50 error messages are being generated, mostly "Novice AI" and "No orders" messages.  When I made this 10 years ago, 50 errors seemed excessive for custom missions turned in to our group.

**Comment by MikeG621** [comment]
Released in [v2.0](https://github.com/MikeG621/MissionVerify/releases/tag/v2.0)
