### ISSUE TITLE
Flight Group ## has no AI.

### ISSUE THREAD

**Issue by keiranhalcyon31** [MikeG621/MissionVerify#3]
Platform: XWA

Any FG with AI skill set to "novice" generates this message.

**Comment by MikeG621** [comment]
That's because "Novice" is zero, that's by design.

--
Michael Gaisser
850-396-4535

**Comment by MikeG621** [comment]
Changing the message to say "basic AI" instead of "no AI", also removing the asterisk which triggers the "might not be valid" message.

**Comment by MikeG621** [comment]
Released in [v2.0](https://github.com/MikeG621/MissionVerify/releases/tag/v2.0)
